version: '3.8'
services:
  service-app:
    container_name: emp_management_service
    build: './'
    image: gawaliniranjan/emp_management_service:gke-mysql-v0
    ports:
      - "5000:5000"
    restart: on-failure