apiVersion: v1
kind: Service
metadata:
  name: emp-mgmt-api-service
  labels:
    name: emp-mgmt-api-service
    app: employee-management
spec:
  type: LoadBalancer
  selector:
    name: emp-mgmt-api-pod
    app: employee-management
  ports:
    - name: http
      port: 5000
      targetPort: 5000
