name: Docker build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPOSITORY: ${{secrets.DOCKER_REPOSITORY}}

jobs:
  create-image-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: workdir
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $DOCKER_REPOSITORY
      - name: Docker Login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker-compose builda
      - name: Push docker image to repository
        run: docker push "$DOCKER_USERNAME/$DOCKER_REPOSITORY:gke-mysql-v1"
  # deployment:
  #   needs: [create-image-and-push-to-dockerhub]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: kubectl - Google Cloud GKE cluster.
  #       uses: ameydev/gke-kubectl-action@master
  #       env:
  #         PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  #         APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA }}
  #         CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  #         ZONE_NAME: ${{ secrets.GKE_CLUSTER_ZONE }}
  #       with:
  #         args: apply -f kubernetes/
